global:
  scrape_interval:     3s
  evaluation_interval: 3s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: objects-service
    metrics_path: /metrics
    static_configs:
      - targets: ['objects-service:8080']
  - job_name: confirmation
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:5016']
  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:5018']
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8000']
